### ISSUE TITLE
2.4.3 Version breaks compatibility with vrcfury + NDMF builder

### ISSUE THREAD

**Issue by BlackCherryCat** [kurotu/VRCQuestTools#31] opened 2024-08-30 14:39 UTC
### Describe the bug / バグの説明

After some tests I see that when I upload an avatar with any vrcfury component in it and with the VQT avatar builder (NDMF) the builder gets an error about wrong materials, but all the materials I use are for quest. The issue is the vrcfury compatibility

### To Reproduce / 再現手順

1. Install vrcfury and NDMF
2. Upload any avatar with a vrcfury component in it using the NDMF feature with VQT avatar builder

### Expected behavior / 期待する動作

Upload the avatar succesfully

### VRCQuestTools version / VRCQuestToolsのバージョン

2.4.3

### Unity version / Unityのバージョン

2022.3.22f1

**Comment by BlackCherryCat** [comment] 2024-08-30 14:44
When my avatar does not have any vrcfury components, it can be uploaded correctly

**Comment by kurotu** [comment] 2024-08-31 02:12
I'm not familiar at VRCFury. What component should I test?
Please describe about your case more specifically.

**Comment by BlackCherryCat** [comment] 2024-08-31 06:13
Any component, try adding vrcfury gestures component at the root of your avatar and then try to upload it with VQT builder and NDMF

**Comment by kurotu** [comment] 2024-08-31 08:05
Thank you for your info, the issue reproduced for me.

v2.4.3 changed the ndmf phase from transforming to optimizing when converting avatars. When using NDMF and VRCFury, NDMF optimizing phase is processed after VRCFury. But VRCFury rejects the avatar because of shaders, so VQT can't perform conversion.

![image](https://github.com/user-attachments/assets/c7a47da7-715b-4403-b871-9c5f97a967f3)

I'm planning to revert the v2.4.3's change. So that VQT can perform before VRCFury as same as before.

**Comment by BlackCherryCat** [comment] 2024-08-31 08:10
We will still having the replacing multiple materials with the same one?

**Comment by kurotu** [comment] 2024-08-31 08:13
At the time of my screenshot, materials are not converted yet. VQT didn't perform because VRCFury rejected the build process.

**Comment by kurotu** [comment] 2024-09-07 07:51
Fixed by v2.5.0.

**Closed by kurotu** 2024-09-07 07:51 UTC

**Comment by Sayamame-beans** [comment] 2024-09-14 23:07
I think this should also be reported to VRCF side?
It is quite possible that there are other tools processing after VRCF (callbackOrder: -10000), and since it is known to actually exist, it can be considered inappropriate to validate the avatar and block the upload at that time.

**Comment by kurotu** [comment] 2024-09-15 08:59
My first investigation was mistake. NDMF optimizing phase runs after VRCFury, but VRCFury automatically removes invalid materials. So VQT can't detect materials to convert and it leads material error on actual devices.
